version: "3.9"
services:
  norgpt3:
    build: .
    # restart: always
    ports:
      - "7779:6000"
    volumes:
      - ./data/all/models/nor_gpt3:/models/nor_gpt3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
